" Use Vim settings
set nocompatible

syntax on
filetype plugin indent on

" Remappings
map <Leader>p :NERDTreeToggle<CR>
map <C-f> gqip " Reflow text
map <F5> :setlocal spell! spelllang=en_ca<CR>
nnoremap <C-Left> :tabprevious<CR>
nnoremap <C-Right> :tabnext<CR>

" Indentation settings (pressing < or > will let you indent/unident selected lines):
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set autoindent

" Will follow Rust's commitment to four spaces.
autocmd Filetype rust setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

set number          " Line numbering...
set cursorline      " A line under the cursor.
set wildmenu        " Press tab for command line completion.
set lazyredraw      " Prevent vim from constantly redrawing everything.
set incsearch       " Search as characters are entered.
set hlsearch        " Highlight matches.
set history=1000    " Keep a loooooooong history.
set visualbell      " No annoying sounds!

" Prevent vim from creating backups.
set nobackup
set nowritebackup

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

