execute pathogen#infect()

" Use Vim settings
set nocompatible

syntax on
filetype plugin indent on

" Indentation settings (pressing < or > will let you indent/unident selected lines):
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
set autoindent

" Line numbering...
set number

set cursorline

set wildmenu

set lazyredraw

set showmatch

" Searching

set incsearch     " Search as characters are entered
set hlsearch      " Highlight matches

set history=1000  " Keep a loooooooong history.

" No annoying sounds!
set visualbell

" Prevent vim from creating backups.
set nobackup
set nowritebackup

map <C-f> gqip

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces

" https://github.com/luochen1990/rainbow

