execute pathogen#infect()

" Use Vim settings
set nocompatible

syntax on
filetype plugin indent on

" Indentation settings (pressing < or > will let you indent/unident selected lines):
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set autoindent

" Will follow Rust's commitment to four spaces.
autocmd Filetype rust setlocal expandtab tabstop=4 shiftwidth=4 softtabstop=4

set number          " Line numbering...
set cursorline      " A line under the cursor
set wildmenu        " ...
set lazyredraw      " Prevent vim from constantly redrawing everything
set showmatch       " ...
set incsearch       " Search as characters are entered
set hlsearch        " Highlight matches
set history=1000    " Keep a loooooooong history.
set visualbell      " No annoying sounds!

" netrw
let g:netrw_banner = 0
let g:netrw_liststyle = 3

" Prevent vim from creating backups.
set nobackup
set nowritebackup

" Remappings

map <C-f> gqip

" Packages

au VimEnter * RainbowParenthesesToggle
au Syntax * RainbowParenthesesLoadRound
au Syntax * RainbowParenthesesLoadSquare
au Syntax * RainbowParenthesesLoadBraces
