#!/bin/bash

mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

cd ~/.vim/bundle

git clone https://github.com/tpope/vim-sensible.git
git clone https://github.com/kien/rainbow_parentheses.vim.git
git clone https://github.com/rust-lang/rust.vim.git
git clone https://github.com/Valloric/YouCompleteMe
git clone https://github.com/eagletmt/ghcmod-vim.git
git clone https://github.com/eagletmt/neco-ghc
git clone https://github.com/ctrlpvim/ctrlp.vim.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/tomtom/tlib_vim.git
git clone https://github.com/MarcWeber/vim-addon-mw-utils.git
git clone https://github.com/garbas/vim-snipmate.git
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/scrooloose/nerdcommenter.git
git clone https://github.com/godlygeek/tabular.git
git clone https://github.com/ervandew/supertab.git
git clone https://github.com/Shougo/neocomplete.vim.git

cd ~/.vim/bundle/YouCompleteMe
git submodule update --init --recursive
./install.py --rust-completer

cd ~/.vim/bundle/
git clone https://github.com/Shougo/vimproc.vim.git
cd vimproc.vim
make


